### ISSUE TITLE
Application Preferences system

### ISSUE THREAD

**Issue by le717** [charlielee/boats-animator#101]
(Brain dump ahead.)

In addition to the individual project system, we should also have an app-wide preferences system for managing stuff that does not only apply to projects.
- JSON based
- Would contain details such as
  - Current theme
  - Any more that fit the above description

Long-term project, no current priority or milestone.

**Comment by BoatsAreRockable** [comment]
Other potential eventual preference details can think of:
* Set default:
  * Audio `on` or `off`
  * Playback fps
  * Onion skinning amount
  * Camera: `source` and `output resolution`
  * Looping: `on` or `off`
  * Framereel collapsed or not.
  * How many frames to play when "play last few" used.
* Custom keyboard shortcuts

**Comment by charlielee** [comment]
Closing this issue as the basis for a preference system has been implemented in the v1.0 rewrite. The settings are exposed on a settings page in #364
