### ISSUE TITLE
Play / loop selection of captured frames 

### ISSUE THREAD

**Issue by charlielee** [charlielee/boats-animator#116]
_Part of #112_

> After selecting a frame 3 more buttons (with keyboard shortcuts) will become available in the playback controls: (These will have icons) "Begin selection", "End selection" and "Unselect". 
> 
> * **Begin selection** - pressing this button after selecting a frame in the framereel will add a _blue?_ vertical line before it and means that after playback stops pressing play will start playback again from this point
>   * If only "begin selection" is used then playback will run from the selected frame to the last frame.
> 
> * **End selection** - this button will be greyed out if "begin selection" hasn't been used yet. Selecting it will add a blue vertical line after it and mean that playback will run from the frame selected with "begin selection" to here.
>   * If the frame selected with this tool is before the frame chosen with "begin selection" then playback will instead run from this frame to the "begin selection" frame.
> 
> * "Unselect" - as its name suggests, pressing this button removes both the start and end selection points
> 
> * The two selection points should eventually be draggable along the frame reel.

I have begun working on this.

**Comment by le717** [comment]
> I have begun working on this.

Can we get the last PR merged and a new release tagged first? I have camera code I want to submit. :D

**Comment by BoatsAreRockable** [comment]
@le717 I've tagged a new release. :smile:

**Comment by charlielee** [comment]
While this is an interesting feature it's not something I plan to implement again in the medium term future, so I will close this issue.

One issue I recall it that it was difficult to create a UI that made this feature make sense and hence something people would actually use. I've also never received any user requests for this.

If anyone wants to implement this in future I would be happy to provide support.
