### ISSUE TITLE
Saved frames should use numbered sequence (with project name) instead of date

### ISSUE THREAD

**Issue by rioforce** [charlielee/boats-animator#13]
The saved frames from the program are labeled by the date and time, in fact, it sets the time as the time I opened the program (for example, if I opened it at 12:30, and took frame at 2:45, it would still label the frames as 12:30), instead of setting it every time a frame is taken. However, I think the program should number the frames by sequence, for example, `ProjectName_0001`. This will help with organization and image sequencing.

**Comment by BoatsAreRockable** [comment]
This seems like a good idea to implement. Although I wonder if the date the frame has been taken should be kept in the frame name? eg: `2015_10_15_ProjectName_0001`

**Comment by rioforce** [comment]
Personally, I don't think the date should be there, seeing how a lot of people animate at night when the day rolls over to the next one. But even more than that, I doubt anyone cares to see what day it was taken on, since that information can be easily accessed through the file explorer. However, I suppose an option could be added for that, but I don't see the need for the date. It looks like it would just get in the way.

**Comment by BoatsAreRockable** [comment]
I think you've convinced me :smiley: I'm just too used to Helium Frog's long frame names. I'll just have to work out how to implement a project naming feature now... And once I do that I'll probably end up trying to implement frame/project importing.

**Comment by le717** [comment]
> I'll just have to work out how to implement a project naming feature now... And once I do that I'll probably end up trying to implement frame/project importing.

I had an idea on how to implement that. I'll try to draw it up and file an issue over the weekend. In the meantime, you can just change the frames to have only the numbered sequence as names.

**Comment by BoatsAreRockable** [comment]
The date has been removed from the frames but project naming is still to be implemented. My idea of a project naming and loading system would be that after selecting a directory, the user selects a project name or perhaps the other way round. Captured frames are prefixed with this project name and small project file listing the location of captured frames, selected camera, resolution, frame rate etc is generated to the project's directory. This would be what file is loaded into Boats Animator.

**Comment by le717** [comment]
Sorry about not getting the project idea I had to you like I said. I have been slammed with things to do (and working on other parts of the program). I'll eventually write the idea up, but TBH, there's more Important parts to tend to right now.

**Comment by le717** [comment]
The in progress label can be removed. This is technically not currently being worked on. ;)

**Comment by BoatsAreRockable** [comment]
This is part of #86
