### ISSUE TITLE
Code indentation

### ISSUE THREAD

**Issue by charlielee** [charlielee/boats-animator#140]
At the moment the codebase is pretty inconsistent when it comes to indentation. I propose that all of the CSS, HTML, JS and JSON files should be converted to have 2 space indents.
#### Files to move to 2 space identation:
- [x] package.json
##### CSS
- [x] about.css (parts)
- [x] animator.css (parts)
- [x] fonts.css
- [x] index.css (parts)
##### JS
- [x] about.js
- [x] file.js
- [x] newsfeed.js
- [x] shortcuts.js
- [x] utils.js
- [x] index.js
- [x] main.js (parts)
##### HTML
- [x] index.html
- [x] about.html
- [x] animator.html

**Comment by le717** [comment]
+1. This is best done gradually, as in, the areas we change in commits should be reformatted.

**Comment by le717** [comment]
What's the status on this now that #198 is merged?

**Comment by BoatsAreRockable** [comment]
I've just updated the checklist in the OP. The `animator.html` and the 3 CSS files left will be reformatted once the `flexbox` branch gets merged. That just leaves `package.json` and `main.js`. `package.json` could easily be reformatted now, just leaving `main.js` which I'd suggest reformatting once `webrtc` is merged.

**Comment by charlielee** [comment]
Following #211 being merged, I have now reindented `main.js` therefore completing this issue!
