### ISSUE TITLE
Listen to directory for updates

### ISSUE THREAD

**Issue by charlielee** [charlielee/boats-animator#143]
A setting where Boats Animator listens to changes to a file directory should be added. When an image file is added to the selected directory it would be added to the `capturedFrames` array and framereel. When this setting was enabled capture mode would simply display a placeholder message. This feature would enable non-supported cameras to use at least some of BA's features.

**Comment by BoatsAreRockable** [comment]
This could potentially be achieved using [Chokidar](https://github.com/paulmillr/chokidar).

**Comment by le717** [comment]
I'm leaning towards [NSFW](https://github.com/Axosoft/nsfw) than Chokidar right now, mainly because it runs on a separate thread and doesn't affect app performance like Chokidar warns about ("so be judicious about not wasting system resources by watching much more than needed").

**Comment by BoatsAreRockable** [comment]
Other than thinking NSFW is a rather unfortunate choice of name 😄, this sounds like a good choice.

**Comment by charlielee** [comment]
I am closing this as it is low priority and unlikely to get implemented. I don't remember ever receiving user requests for this.

If anyone wants to implement this in future I would be happy to provide support.
