### ISSUE TITLE
UI tidy up and sidebar enhancements

### ISSUE THREAD

**Issue by charlielee** [charlielee/boats-animator#183]

**Comment by le717** [comment]
I have yet to pull the code so I can't say for sure, but didn't you remove the sidebar in #198? If so, this can be closed.

**Comment by BoatsAreRockable** [comment]
@le717 the sidebar still remains, in #198 I just removed the capture placeholder links that were there.

The sidebar currently in `master` currently just displays the current export directory with the option to change it. Although the `webrtc` branch adds `select` elements for resolution and camera source to it.

**Comment by charlielee** [comment]
As an addition to this, with the increasing amount of options on the sidebar, tabs should also be added.

Perhaps something similar to that of VS Code's sidebar. When collapsed the sidebar should only show the icons for each tab

**Comment by charlielee** [comment]
Mockup:

![screencapture-charlielee-uk-ba-mockups-sidebar-2021-03-20-09_54_55](https://user-images.githubusercontent.com/8095888/111866031-5de4ad00-8962-11eb-8814-1efaee2b707b.png)
