### ISSUE TITLE
Refactor html and css

### ISSUE THREAD

**Issue by charlielee** [charlielee/boats-animator#189]
I'd like to refactor the HTML and CSS used in Boats Animator a bit:
* There are currently `div` elements used as `#main-event`, `#sidebar`, and `#statusBar` - these should be moved to their HTML5 semantic equivalents  (`main`, `aside` and `footer`).
* Generally div usage should be reduced, for instance each button in the playback controls is currently a `div` - these should be moved to buttons with `-webkit-appearance: none`.
* Simplify the HTML by potentially moving control panels in `animator.html` from tables use Flexbox.
* Is `#sidebar-content` needed as well as `#sidebar`? 
* There are a number of common elements to the index, about and animator pages. Styles such as sidebar and footer should be moved from being duplicated across 3 different style-sheets to a general `common.css` file.
* When these changes are implemented a significant amount of progress on the switch to 2 spaced indentation (#140) should be made.

**Comment by BoatsAreRockable** [comment]
Update:
* Most of the major semantic element moving and `common.css` work was done in #198 
* Currently I am working on moving a number of different parts of the interface over to flexboxes in the `flexbox` branch.
* I am also further tidying up the html and css.

**Comment by BoatsAreRockable** [comment]
I am shortly due to merge the `flexbox` branch as #208. This will just leave the following point in the OP:
> Generally div usage should be reduced, for instance each button in the playback controls is currently a div - these should be moved to buttons with -webkit-appearance: none.

**Comment by charlielee** [comment]
I think this is low priority and hence can be closed. Reducing div usage is no bad thing but can be done as parts of the program get updates.
