### ISSUE TITLE
Switch keyboard shortcut library

### ISSUE THREAD

**Issue by charlielee** [charlielee/boats-animator#201]
At the moment keyboard shortcuts in Boats Animator are handled via a weird mix of NW.js's built in [shortcut](http://docs.nwjs.io/en/latest/References/Shortcut/) library and some keys and modifiers associated with some [menu items](http://docs.nwjs.io/en/latest/References/MenuItem/).

I want to continue using the shortcuts with **MenuItems** since they display what the shortcut keys associated with them in quite a nice fashion:

![image](https://cloud.githubusercontent.com/assets/8095888/24809044/2bde563a-1bb6-11e7-9097-0fe6e54d2768.png)

However, we need to replace our usage of the **Shortcut** library for non MenuItem shortcuts. The main reason is that this feature was designed for assigning global hotkeys and we only need to assign local hotkeys. Currently there are functions within `shortcuts.js` that "pause" and "resume" the global shortcuts when it is detected that a user is outside of Boats Animator. However I have found this to be quite unreliable and bug prone, without there being any benefits.

A quick search brings up [Mousetrap](https://craig.is/killing/mice) or [Keymaster](https://github.com/madrobby/keymaster) as possible libraries to use.

Mousetrap seems pretty powerful with extensions such as shortcut recording being quite useful in future when custom shortcuts are implemented. Comparatively Keymaster seems to have fewer features. I looked at Mousetrap before and I have to say I am slightly kicking myself for not implementing it instead of the NW.js shortcut api.

**Comment by BoatsAreRockable** [comment]
This needs to be of high priority because the current behaviour of often failing to "pause" shortcuts when the application is not in focus is really a bug.

**Comment by charlielee** [comment]
Working on this in the `mousetrap` branch
