### ISSUE TITLE
Export to video

### ISSUE THREAD

**Issue by charlielee** [charlielee/boats-animator#203]
Eventually the ability to export a project's captured frames to video should exist. At the moment when playback occurs a canvas animation occurs and one way of turning this into a video would be using https://github.com/antimatter15/whammy, although this would only allow WebM videos to be exported.

A more flexible way I can see us eventually considering would be using a combination of two different Web APIs that both seem to be pretty experimental:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/captureStream
https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/MediaRecorder

**Comment by BoatsAreRockable** [comment]
If we need used Whammy, Handbrake-js could then be used to encode the `WebM` video to other video formats. https://github.com/75lb/handbrake-js

Btw I should empathise that this feature is a very low priority right now. Individual frames output is perfectly adequate since most editing programs support image sequence importing.

**Comment by charlielee** [comment]
Recently I came across this JavaScript port of FFmpeg which could used for the video export function:
https://github.com/Kagami/ffmpeg.js

Whammy seems to not be actively maintained and FFmpeg.js is far more versatile and even supports things such as Web Workers. Here's an example of FFmpeg converting an image sequence to video:
http://hamelot.io/visualization/using-ffmpeg-to-convert-a-set-of-images-into-a-video/

**Comment by DerJacques** [comment]
Great project! 
Did you by any chance stumble upon [Videoshow](https://www.npmjs.com/package/videoshow) during your research?  
I think it would be perfect for boats-animator. The only thing I'm not certain about is how easy it is for you to include ffmpeg in your application. That being said, you would probably experience the same issue using ffmpeg.js.

**Comment by charlielee** [comment]
> Great project!

@DerJacques thank you very much, although there is still much to do!

> Did you by any chance stumble upon Videoshow during your research?
I think it would be perfect for boats-animator.

No I haven't seen Videoshow before, thanks for pointing it out! 😄 I have just been experimenting with it and it definitely seems very promising. It certainly removes a lot of the complexity of using FFmpeg. So far, my only concern with it is that each image of the video has a duration set in seconds rather than frames. Since each frame in stop motion is very short I am concerned that this could lead to dropped frames in the output video. Also it could lead to longer videos being slightly longer or shorter than expected

> The only thing I'm not certain about is how easy it is for you to include ffmpeg in your application. That being said, you would probably experience the same issue using ffmpeg.js.

To get Videoshow to work on my Windows machine I had to [download FFmpeg](http://ffmpeg.zeranoe.com/builds/) and then I copied `ffmpeg.exe`, `ffprobe.exe` and `ffplay.exe` from the downloaded archive to the same directory where my JavaScript file was. I'm sure this would be relatively straightforward to implement as part of the build process but it would require a slightly different approach for each OS.

FFmpeg.js would not require something similar because it is a complete port of FFmpeg to JavaScript. However, we would not be able to benefit from how much easier Videoshow makes things and some testing would be needed to see if there was a significant performance drop over natively using FFmpeg.

**Comment by DerJacques** [comment]
I didn't quite catch that FFmpeg.js is a complete port. That's impressive!

It's a shame that Videoshow uses seconds as the measurement for duration. I agree that this may potentially cause some issues due to the high FPS of stop motion videos (compared to their use-case: video slide shows). Unfortunately, I haven't used videoshow before, so I'm not sure if there's a way to work in `ms`.

I think it's a great idea to keep on experimenting a bit, since it seems videoshow potentially could make your life a bit easier if it works out!

**Comment by charlielee** [comment]
I've concluded that the best approach would be to use [fluent-ffmpeg](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg) rather than Videoshow. fluent-ffmpeg is what the Videoshow is built on top off and still makes things a lot easier than using pure ffmpeg commands. But nevertheless, thanks for suggesting Videoshow @DerJacques because it directly helped me find fluent-ffmpeg! :)

**Comment by le717** [comment]
Just remember that while it's good to research and keep log, this is pretty low-priority ;)

**Comment by charlielee** [comment]
While low priority, this would be quite straightforward to implement once #37 and #213 are completed. I should also add that it is by far the most requested feature by users.

**Comment by charlielee** [comment]
This has been in progress for a while on the `exportVideo` branch. I've experienced quite a few bugs and general confusion with fluent-ffmpeg so this won't be used.

As a result this will be implemented with https://github.com/kribblo/node-ffmpeg-installer to get the correct ffmpeg binary, and then simply a node child process.

**Comment by charlielee** [comment]
The main thing that needs sorting is handling including the appropriate ffmpeg binary during build by running `npm install --production`. This is being worked on in https://github.com/charlielee/nwjs-packager/issues/3

**Comment by charlielee** [comment]
Implemented in #258
