### ISSUE TITLE
Handled cameras being plugged in and removed

### ISSUE THREAD

**Issue by charlielee** [charlielee/boats-animator#204]
The program should be able to handle cameras being added or removed. Chromium 57 adds the `ondevicechange` event listener (we are currently on Chromium 55):

https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/ondevicechange

**Comment by le717** [comment]
I really need time to work on the camera code. I could integrate this very easily once the mass of camera code is in place.

**Comment by BoatsAreRockable** [comment]
@le717 I actually started working on the camera code again yesterday and today (see the `webrtc` branch). Currently I've got source changing implemented.

**Comment by charlielee** [comment]
Implemented in #211!
