### ISSUE TITLE
Create generic popup window class

### ISSUE THREAD

**Issue by charlielee** [charlielee/boats-animator#213]
This will be useful for video export #203, the Application Preferences system #106 and projects #86 amongst other things. These popsup could also be used for refactored confirm dialogs.

I actually did I a lot of the work required for this a while back in the form of: https://github.com/charlielee/native-ui-panels

For some reason I can't currently work out how to display panels created using `native-ui-panels`, but I should be able to either reuse of a lot of code I wrote for this or work on improving the module for use with Boats Animator.

**Comment by charlielee** [comment]
A couple of possible options:
https://robinparisi.github.io/tingle/
http://chieforz.github.io/popupS/

My first impression is that Tingle would work well, but I will do some testing.

I will also link to Smalltalk. This only offers a replacement for the dialogs:
https://github.com/coderaiser/smalltalk

**Comment by charlielee** [comment]
More options:

https://limonte.github.io/sweetalert2/
https://anseki.github.io/plain-modal/
http://humaan.com/modaal/

**Comment by limonte** [comment]
> https://limonte.github.io/sweetalert2/

this link is outdated, here's the correct one https://sweetalert2.github.io/

**Comment by charlielee** [comment]
Been looking at these libraries again, probably going with SweetAlert2. Tingle is a close second.

**Comment by le717** [comment]
I've implemented https://sweetalert.js.org/ at work and would 100% replace any custom things we have with it. I don't know the difference (or relation) between it and SweetAlert2, though

**Comment by charlielee** [comment]
I have done some snooping and found out that SweetAlert2 is a fork of SweetAlert 1.x, which has since gained a version 2.x. Confusing right! 

The SweetAlert2 fork was made at a point when the original was unmaintained:
https://stackoverflow.com/questions/26838965/sweet-alert-display-html-code-in-text/27842854#27842854

But since the original is being maintained again these days, I'd say let's just use that.

**Comment by charlielee** [comment]
Implemented in #229
