### ISSUE TITLE
On playback, the last frame captured is displayed before the first frame

### ISSUE THREAD

**Issue by charlielee** [charlielee/boats-animator#217]
Ie for 5 frames the order they would be displayed on playback is "5, 1, 2, 3, 4, 5".

**Comment by le717** [comment]
I know why this is occurring and it's still occurring in #211 so it'll be best to fix there or after it's merged. Basically, when the live preview is hidden and the playback window is shown, there's a second delay after that happens before the playback starts, hence frame 5 (for example) is visible. IDK how to fix it. Oddly, it often only occurs the first time playback is initiated and is not present on subsequent plays.

**Comment by charlielee** [comment]
Implemented a fix in PR #217
