### ISSUE TITLE
Remember the size and position of windows and restore them in that place after app relaunch

### ISSUE THREAD

**Issue by charlielee** [charlielee/boats-animator#219]

**Comment by charlielee** [comment]
Should be able to achieve this with the id option of window.open https://docs.nwjs.io/en/latest/References/Window/#windowopenurl-options-callback

**Comment by AndreasDemenagas** [comment]
I have a solution almost ready. Should I move forward with a PR?

**Comment by charlielee** [comment]
Yes please :)
