### ISSUE TITLE
Bump to NW.js v0.35

### ISSUE THREAD

**Issue by charlielee** [charlielee/boats-animator#222]
And deal with any issues that come as a result!

**Comment by le717** [comment]
Tbh, this might have to happen sooner than later because a lot of woek

**Comment by le717** [comment]
TBH, this might have to happen sooner than later (as in, in 0.8.x), because a lot of work from here on out requires newer apis only available and newer versions.

Didn't mean to close this... 😬

**Comment by charlielee** [comment]
I will start this after #224 and #227. Alternatively we could start nwjs35 work in a separate branch and push 0.9.0 stuff to there.

**Comment by charlielee** [comment]
I['m going to release 0.8.1 now and then do the nwjs version bump.

**Comment by charlielee** [comment]
Implemented in #232
