### ISSUE TITLE
Store Camera.list in local storage

### ISSUE THREAD

**Issue by charlielee** [charlielee/boats-animator#227]
I think we should store the supported resolutions of detected cameras between sessions, as the device media ID associated with a camera seem to stay the same between sessions. 

This would mean that the resolution selection loading screen would only need to happen the first time each camera is detected, rather the the first time every session. The last resolution used could also be stored.

Cameras with no resolutions detected (due to an error or the user never selecting them) would not be stored between sessions.

The eventual preferences screen could have #101 could have a "Reset Device List" option.

**Comment by charlielee** [comment]
I'm currently working on this. Once this and #224 are implemented, I'll release v0.8.1.

**Comment by le717** [comment]
I'm not actually sure if localSession is persisted across app launches. I know I store a cached version of the newsfeed in it but I don't actually know if it is persistent. Do a quick check to confirm it is persistent before going further

**Comment by charlielee** [comment]
Can confirm that `localStorage` is persistent, while `sessionStorage` isn't :smile:

**Comment by le717** [comment]
Completed by #230.
