### ISSUE TITLE
Unable to open v0.8.0+ in macOS 10.14

### ISSUE THREAD

**Issue by charlielee** [charlielee/boats-animator#248]
BiM user CEESLegoProductions messaged me last week to saying that they were receiving the following message when trying to open the program on macOS:
![image](https://user-images.githubusercontent.com/8095888/61286196-45e67e80-a7ba-11e9-8937-c49268952e31.png)

I have finally gained access to a macOS 10.14 installation and sure enough the same issue occurs. It seems to be affecting all builds including and after v0.8.0. Running the application from source on 10.14 with `npm start` seems to be working fine however.

With an issue like this there's so many variables:
1. Is it an issue with nwjs-builder? Our packaging tool that I've been meaning to replace.
2. Is it only an issue on  macOS 10.14?
3. Is it only an issue with our current version of NW.js?

I think it's going to take a while for me to figure this out. Especially as a non-Mac user!

**Comment by le717** [comment]
I have an older iMac at home, idk current macOS version. I _might_ be able to test part of this on it, time and schedule permitting. No promises though

**Comment by charlielee** [comment]
I found the source of the issue  (I think?).
https://github.com/nwjs/nw.js/issues/7017

Adding `"product_version": nwjs` to `package.json` seems to fix things. I will have to do further testing. Obviously this is something our build tool should sort, but for now we hopefully have working Mac builds again.

**Comment by charlielee** [comment]
This seems to have been fixed by the change to package.json
