### ISSUE TITLE
Boats Animator partnership with umbrella organization

### ISSUE THREAD

**Issue by FinixFighter** [charlielee/boats-animator#255]
Hi! I was thiking that maybe you could be interested in becoming part of an umbrella organization such as Software Freedom Conservancy (https://sfconservancy.org/) or Public Software (https://publicsoftware.eu/) so that you can focus on software developing without struggling with the bureaucratic aspects; moreover, by being part of such an organization, Boats Animator will be able to accept donations, so that developers will be more motivated to improve the software.
What do you think about it? :)

**Comment by charlielee** [comment]
Hey @FinixFighter thanks for creating this issue. I've had a look at the links you suggested. They look really interesting however I'm not sure joining an organisation is right for this project at this time.

Boats Animator is a small application with no more than a couple of hundred active users and is almost solely maintained by myself.

Should the application grow to be much larger I will definitely reconsider umbrella organisations. :)

**Comment by FinixFighter** [comment]
Understood! Thank you so much for your reply! And keep up the good work! :D
