### ISSUE TITLE
Boats-Animator on Flathub

### ISSUE THREAD

**Issue by FinixFighter** [charlielee/boats-animator#264]
Hi! I was wondering if a flatpak version of boats-animator will be available in the future. It would be very useful to already have it in the repositories. Moreover, I think it would be easier to find it, reaching more people :)

**Comment by charlielee** [comment]
I would like Boats Animator to be as easy to get as possible. Any packaging required for additional  distribution formats will be implemented through our packaging tool https://github.com/charlielee/nwjs-packager

I haven't considered which formats will be used yet but I will bare Flatpak in mind. 🙂

**Comment by charlielee** [comment]
I'm closing this issue because it is something for nwjs-packager

**Comment by basstwo** [comment]
Can I get more information on this?  I am new to a lot of this information.  My son has a laptop that runs Endless OS.  I am used to getting apps on it via Flathub.  I got some help from the Endless OS community to get Boats installs and working.  But the final step, exporting to video, doesn't work properly form with in the app.  I have to have him run ffmpeg from the terminal and copy/paste the commands from the export video dialog box.  Is there anything that can be done to remove this requirement so it is easier for him to use Boats?

**Comment by charlielee** [comment]
Hi @basstwo,

I am currently in the process of moving this app to use Electron (issue #274) and the build tool `electron-builder`. That tool doesn't appear to support flatpak out of the box but when that work is complete I may be able to find a work around.

In Boats Animator, you press the blue "Export video" button, would you be able to send me the output in the dialogue that appears afterwards?

Thanks

**Comment by basstwo** [comment]
I don't have that option right now.  But here is a link ot the helpful post that shows a screenshot and gave me the steps I needed to take.
https://community.endlessos.com/t/installing-a-ubuntu-app/15433/9

**Comment by charlielee** [comment]
@basstwo I have tested export video on Ubuntu 20.04 today and am also experiencing errors. Looks like this an issue affecting Linux build of the app in general.

I have created issue #279 to track this bug. Thanks for bringing it to my attention
