### ISSUE TITLE
Move to Electron

### ISSUE THREAD

**Issue by charlielee** [charlielee/boats-animator#274]
This project should be moved to Electron. Some of the main reasons I wish to move are:

* NW.js is missing a solid build/packaging library
* NW.js doesn't properly implement camera permissions, making macOS support feel slightly hacky (there is not an equivalent to Electron's [systemPreferences](https://www.electronjs.org/docs/api/system-preferences#systempreferencesgetmediaaccessstatusmediatype-windows-macos) api)
* Electron seems better supported and to have a much larger developer eco-system

Over the years of this project's development Electron has become far more popular and feature filled than NW.js. It has a large the eco system of packages and other tools around it that we could take advantage of. Whereas NW.js doesn't even have a reliable build library. I have developed the [nwjs-packager](https://github.com/charlielee/nwjs-packager) library but it requires a lot more work to be even close to something like https://github.com/electron-userland/electron-builder.

I would rather spend my free time developing this app, then working on build tools. This will be a big job but I think it will be worth it.

I will start experimenting with how this will work soon. Other features such as projects can be developed normally still and we will have to work out how to port them to the Electron branch

**Comment by AndreasDemenagas** [comment]
I completely agree with moving the project to electron. It is true that it is way more developed than nwjs and I believe it can really help the project. 

Also, the refactoring of the code into modules that you have done should really help make it easier to make an electron build.

**Comment by charlielee** [comment]
NW.js specific features we currently use:

#### nwdirectory

Adding the [`nwdirectory`](https://nwjs.readthedocs.io/en/latest/References/File%20Dialogs/#featured-extended-by-nwjs) attribute to the "choose directory" option allows the app to get the full path of a chosen directory

#### Menu

The `Menu`/`MenuItem`/`nw.Window.get().menu` options are used to generate the top menu bar shown.

https://nwjs.readthedocs.io/en/latest/References/Menu/

#### Shell

`nw.Shell.openExternal(url)` is used to open links from the news section, about window and help menu.

https://nwjs.readthedocs.io/en/latest/References/Shell/

#### Window

The window

**Comment by charlielee** [comment]
Currently working on this with a very basic electron and electron-builder setup. Lots of boilerplates/tutorials suggest adding things like webpacker, react or testing suites. These are interesting things to consider for the future but outside of this issue's scope
