### ISSUE TITLE
Export Folder name cannot have spaces

### ISSUE THREAD

**Issue by geoffdawkins** [charlielee/boats-animator#277]
Hi
Brilliant stop frame software - I really like it and shall be using it with my students.

One issue is that the program fails to save the exported animation video if the output folder has spaces in it (Windows).  Adding quotation marks around the folder name in the ffmpeg export command would solve this, I suspect.
Regards
Geoff

**Comment by charlielee** [comment]
Thanks for reporting this @geoffdawkins

**Comment by charlielee** [comment]
This is fixed in v0.10.1
