### ISSUE TITLE
Video export doesn't work on Linux builds

### ISSUE THREAD

**Issue by charlielee** [charlielee/boats-animator#279]
This only occurs after building the app. Video export works fine when you run the app from the source code with `npm start`.

I built the app with the SDK version of NW.js and got the following error upon video export:

![image](https://user-images.githubusercontent.com/8095888/102391782-1569cc00-3fce-11eb-8f4e-3e09160ec65c.png)

The export modal itself is blank:

![image](https://user-images.githubusercontent.com/8095888/102392043-77c2cc80-3fce-11eb-8374-ba291104fb7d.png)

I suspect this is some permission weirdness with the ffmpeg binary in the production version.

**Comment by charlielee** [comment]
This should be fixed in v0.11.0. We are changing from NW.js to Electron #282 and the Electron packaged Linux builds do not appear to have this issue.

**Comment by basstwo** [comment]
Excellent!  Will there me instructions on how to install?  I am still very new to Linux and Electron.  :)

**Comment by charlielee** [comment]
The next version will be available in a `.deb` package, and also simply a `.taz.gz` archive. It should be realised in the next couple of days.

I am still investigating other formats such as AppImage, Flatpak and Snap for the future.
