### ISSUE TITLE
Naming directories with space don't export properly

### ISSUE THREAD

**Issue by DaNickster37** [charlielee/boats-animator#280]
It appears the formatting of the code to export images to video leaves open the issue that it won't properly read the files if there's a space in the name. I temporarily fixed it by replacing space with _.

**Comment by charlielee** [comment]
@DaNickster37 which version of the app are you using? I have just released 0.10.1 which was intended to fix this problem. Thanks

**Comment by charlielee** [comment]
@DaNickster37 are you still experiencing this issue on version 0.10.1 or can this issue be closed?

**Comment by DaNickster37** [comment]
> 
> 
> @DaNickster37 are you still experiencing this issue on version 0.10.1 or can this issue be closed?

It appears I am not experiencing any issue with spaces anymore, sorry for not responding to previous comment.

**Comment by charlielee** [comment]
No problem! ☺️
