### ISSUE TITLE
Remaining frames don't rename when you delete some

### ISSUE THREAD

**Issue by basstwo** [charlielee/boats-animator#283]
If I take 10 frames and then delete frame 5 I end up with mine frames but the are numbered up to 10 and 5 is missing. This causes an error in the ffmpeg arguments as it tries to look for frames 1-9 but can't find 5.  And the resulting video is missing the last frame.

**Comment by charlielee** [comment]
Hi @basstwo there is a "confirm take" option that will rename the files correctly. You can run it via `Capture > Confirm Take`.

This function runs automatically when "export video" is selected. However, I know you have had issues with export video #279.

**Comment by basstwo** [comment]
Thanks!  I will test this out later today!

**Comment by charlielee** [comment]
Hi @basstwo, can this issue be closed now? Thanks 🙂

**Comment by basstwo** [comment]
Yes, thanks!
