### ISSUE TITLE
Electron builds cause duplicate entries in start menu

### ISSUE THREAD

**Issue by charlielee** [charlielee/boats-animator#284]
In the next version we will move to electron and electron-builder. It uses NSIS rather than Inno Setup for Windows installers.

Sticking with Inno Setup is not an option, as I want to reduce the overhead of the packaging process.

As a result there is the fun consequence that there will be duplicate start and uninstall entries:

![image](https://user-images.githubusercontent.com/8095888/106525697-4baace80-64dc-11eb-8903-9eec90a49c00.png)

![image](https://user-images.githubusercontent.com/8095888/106525721-56656380-64dc-11eb-8eaa-a90bbf031a6c.png)

Some options I can think of to reduce confusion:

1. Add some check in the installer for the Inno/NW.js versions and prompt the user to uninstall them before proceeding
2. Move ahead with #197 and use a different icon for the next version of Boats Animator. 
3. Show a different name in the start menu / uninstall for the next version like "Boats Animator 2"

I'm a bit reluctant to bother with **Option 1**, unless it's really easy. We'd be stuck with extra logic in the build process that will only ever be needed once.

**Option 2** is pretty viable. My favourite logo in #197 is still legoguy501's contribution to that issue from 2017. I can probably try and digitising it, unless someone wants to try since I'm not much of an artist!

I'm in two minds about **Option 3**.  I guess this could it help smooth the transition a bit. Makes the program look more mature too! 

If nothing was done about this issue, it wouldn't be that big of a deal, but it would save me a few emails from confused users. 😆

**Comment by le717** [comment]
I'm going to recommend option 4: Automatically uninstall the previous version if it exists. Although it seems it could possibly get a bit [weird](https://stackoverflow.com/a/22353131), it is possible to trigger InnoSetup uninstallations from the command line/through a batch script. Basically, you need to read the install path of the previous version from the registry and if you get it, run the uninstall exe with the `/SILENT` flag to remove the "are you sure" prompt.  You  would make it part of the NSIS installation, like in the "before install" part of the process. This ensures the old version is removed before the new one is added. You'd have to keep this a part of the installation process for a bit but I think it's worth it.

**Comment by charlielee** [comment]
I've made a start with this in #282. Not got it working yet.
