### ISSUE TITLE
Set a donation method

### ISSUE THREAD

**Issue by FinixFighter** [charlielee/boats-animator#315]
Hi! I like a lot this project and I think it has so much potential. I was wondering: why don't you ask for donations? You could also set milestones and use money to boost the project in different ways.

**Comment by charlielee** [comment]
To do:
- [ ] Add a link to Ko-fi on charlielee.uk https://github.com/charlielee/charlielee.github.io/issues/23
- [ ] Add a link to Ko-fi to the README file

I'm keen not to overly nag people, so I don't have any plans add a donation link into the app itself.
