### ISSUE TITLE
Confirm Take option

### ISSUE THREAD

**Issue by rioforce** [charlielee/boats-animator#37]
When you delete a frame from within Boats Animator, it deletes it from the files and still seamlessly plays back the frames in-program. This is fantastic. However, when you try to import those frames into a video editing program as a video sequence, it will break on the missing frame (for example, `IMG_0001`, deleted `IMG_0002`, it can't get past 0001).

Thus, if you add a button in the file menu called "Confirm Take", it will just fix the image sequence by renaming all the pictures in the sequence to be sequential once again. However, this will be different than "Save Project", for someone may not want to confirm the take every time they same the project (there are various reasons for this).

**Comment by BoatsAreRockable** [comment]
I hadn't considered this issue before, I shall try to figure out the best way to implement it.

**Comment by charlielee** [comment]
Implemented this! :D
