### ISSUE TITLE
By default new frames are should be added after the selected one

### ISSUE THREAD

**Issue by MrMe1024** [charlielee/boats-animator#433]
Sometimes when making stop-motion you don't realize that a frame is bad until latter. As a result it would be really useful to have a feature that made it so new frames are always put after the selected frame. this way I could replace bad frames with new ones without deleting all of the ones that came after it. It would also be helpful if the onion skining looked at the frame selected (or the last frame if prevew is selected) so it would still work for adding frames in to the middle of the protect too.

**Comment by charlielee** [comment]
Thanks for creating this issue. This is an interesting idea, however I think it would be simpler if the ability to move frames around was added. This would still allow you to fix bad frames.
