### ISSUE TITLE
Launch webcam controller on opening new project

### ISSUE THREAD

**Issue by charlielee** [charlielee/boats-animator#76]
Legoguy501 on Bricks in Motion also suggested this interesting feature. An option to specify a controller/utility program (such as Logitech Webcam Controller) to open on launching a new project could be very handy. In addition for known applications the animator window could resize to fit the controller

**Comment by le717** [comment]
Opening a specified controller utility is 100% possible. See also: http://stackoverflow.com/questions/22375039/trying-to-start-exe-application-from-node-js, http://www.hacksparrow.com/difference-between-spawn-and-exec-of-node-js-child_process.html

As for resizing the window...eh, we'll see about that one.

**Comment by le717** [comment]
This is dependent on #101.

**Comment by charlielee** [comment]
I am closing this issue because I don't think it is a feature that many users would use. Eventually implementing a way to control cameras from within the app via UVC controls #240 or webrtc/imagecapture api #205 would also make this mostly unnecessary.
