### ISSUE TITLE
Built-in updater

### ISSUE THREAD

**Issue by le717** [charlielee/boats-animator#80]
I had an idea. :P

Help>Check for updates in menu. Pull the GitHub API for the repo and grab the latest release. If version stated is newer than internal version (we'd need to setup some `const` value for that), prompt to download. If yes, install it (there's more to that obviously). If equal, say so.

No milestone needs to be set or anything (I _really_ need to get back to work on this...). Just an idea I'd toss at you. :)

**Comment by BoatsAreRockable** [comment]
This sounds like an interesting idea! I'd like to see this eventually implemented

**Comment by le717** [comment]
I found something that might help out with this. We'll see later (this issue has zero priority right now). https://github.com/edjafarov/node-webkit-updater

**Comment by BoatsAreRockable** [comment]
This could be useful if we want to have the option to allow "beta tester" users to pull straight from master:
https://github.com/ianstormtaylor/download-github-repo

**Comment by le717** [comment]
The NW,js docs now has some suggestions for an auto-update system: http://docs.nwjs.io/en/latest/For%20Users/Advanced/Autoupdates/

**Comment by charlielee** [comment]
I am considering closing this issue. An auto-updater would likely be implemented into [nwjs-packager](https://github.com/charlielee/nwjs-packager).

**Comment by le717** [comment]
Then close it. :wink:
