### ISSUE TITLE
Create Mac DMG

### ISSUE THREAD

**Issue by charlielee** [charlielee/boats-animator#81]
Currently Inno Setup provides us with a solid Windows installer, however there are Mac and Linux users to consider too. Should we perhaps consider moving to a more cross platform solution such as BitRock InstallBuilder?

**Comment by le717** [comment]
Macs use .dmg installers (can be created only a Mac) (that is, when software uses an installer), and traditionally Linux does not use installers (only .zip archives). It is only Windows that has predominant installer usage.

**Comment by klokie** [comment]
Hi, I just downloaded and tried to install release v0.7.4 on my Macbook running OS X El Capitan (10.11.6). First I got an "unknown error" but from the console saw that it was just that the executable bit needed to be set on `BoatsAnimator.app/Contents/MacOS/nwjs`. But then when I try to run the app it crashes immediately. I've pasted the log here:

[Mac OS 10.11.6 crash log from BoatsAnimator.app](https://gist.github.com/klokie/c0ee047a3ca453d531891d121d1d78fe)

**Comment by BoatsAreRockable** [comment]
Thanks for reporting this @klokie. I have quite limited access to macOS, however I shall see if I can replicate this next time I'm around one of my university's iMacs which are believe are running El Capitan. This may be an issue more do to with NW.js than Boats Animator so I'll see if I can find anyone who has been affected.

**Comment by charlielee** [comment]
I have just applied to BitRock InstallBuilder for a free open source license. It makescross-platform installers, .deb and .rpm amongst other features. While an installer is less "native" than a DMG, it makes most sense when I do not have regular access to a Mac.

https://installbuilder.bitrock.com/open-source-licenses.html

An open-source alternative to BitRock would be preferable, but there do not seem to be any viable alternatives. And one solution for all platforms would reduce the workload of distribution.

**Comment by charlielee** [comment]
BitRock have just provided me with an InstallBuilder license. At some point I shall try it out and see if it's right for this project. 😄

**Comment by charlielee** [comment]
Closing this issue as .dmg support will be a concern for my nwjs-packager project going forward. https://github.com/charlielee/nwjs-packager/issues/1
