### ISSUE TITLE
Revise confirm dialog behavior

### ISSUE THREAD

**Issue by le717** [charlielee/boats-animator#82]
Spun off https://github.com/BoatsAreRockable/animator/pull/70#issuecomment-152787716.

> The `confirm()` API was intentionally written to return true or false depending on the button clicked because it is generic and supports many uses cases. While currently our use case is a simple "if yes, run function else do nothing", thinking long term this may not be the case and this code will have to be refactored to support it. I am thinking it would be better to refactor this to copy the generic behavior of `confirm()` to support future use cases.

**Comment by BoatsAreRockable** [comment]
Adding to this, the "OK" button in confirm dialogs should be focused by default - allowing the user to press enter to select it.

**Comment by BoatsAreRockable** [comment]
Another improvement that should be made to confirm dialogues is that the HTML tabindex method be used to switch between the OK and cancel buttons:

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

**Comment by charlielee** [comment]
This is linked to the introduction of a new pop window class (issue #213)

**Comment by charlielee** [comment]
Implemented in #229
