### ISSUE TITLE
Changing video sources

### ISSUE THREAD

**Issue by charlielee** [charlielee/boats-animator#84]
Currently there is no way of switching camera if multiple are connected, this is something that needs to be eventually implemented. `MediaStreamTrack.getSources()` appears to be the best way to achieve this using HTML5.

**Comment by le717** [comment]
I've also been toying with this. This came out much better than I expected and I already have a workable camera selection implementation.

**Comment by le717** [comment]
I'm having to rewrite a good chunk for this and #92, as it seems I lost a lot of it in upgrading to Windows 10. :( However, it seems NW.js is super buggy when it comes to WebRTC and Windows 10. I was getting much better results on Windows 7. We might need to prioritize #108 even though 0.13 is still in beta.

**Comment by BoatsAreRockable** [comment]
I'm sorry to hear that :( I'm happy to prioritise #108 if you think 0.13 would help fix this!

**Comment by le717** [comment]
Note for me: nw.js 0.13 is getting Chrome 49 so this should not affect us, but Chrome 50+ now has <audio> and <video> tags make `.play()` return a promise. Once we get Chrome 50 we'll need to support this, but it should not be too much of an issue. https://developers.google.com/web/updates/2016/03/play-returns-promise

**Comment by charlielee** [comment]
Implemented in #211!
