### ISSUE TITLE
Project system

### ISSUE THREAD

**Issue by le717** [charlielee/boats-animator#86]
Another brain dump incoming. As always, anything is up for discussion.
- [JSON-based](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON)
- Ends in Boats-unique extension for (at least on Windows) shell registration (click the file and Boats opens it)
- Contains following details
  - Project name
  - Description
  - Author name
  - Creation date
  - Frame save path (default: `/frames`)
  - FPS
  - Number of captured frames
- Absolute paths are not stored to enable portability (just copy the project files and use it anywhere)
- Able to frames outside project folder (state such is not recommended to user)
- If required to create external path, info notification saying so
- Anything else I'm missing (I'll edit this issue as needed)

**Comment by rioforce** [comment]
Solid idea, but it is missing takes. Often, someone will want to use the same project and capture more than one take, shot, or even scene without making a new project. Thus, the main project should be a folder, inside should be a folder for each take (which would include the frames, and if a specific json was needed for each take, the frames would be in a subfolder).

**Comment by BoatsAreRockable** [comment]
https://github.com/nwjs/nw.js/wiki/Handling-files-and-arguments

**Comment by BoatsAreRockable** [comment]
https://support.microsoft.com/en-us/kb/184082

https://msdn.microsoft.com/en-us/library/cc144158%28VS.85%29.aspx?f=255&MSPPError=-2147217396

**Comment by le717** [comment]
Dude, I've created file associations with Inno Setup before, [it is really easy](https://github.com/le717/PatchIt/blob/rewrite/Tools/Windows/PiInstaller.iss#L120-L125). :)

**Comment by BoatsAreRockable** [comment]
Oh sweet :) what about Mac/Linux though? Is this something we could only do once we have a dmg/deb/rpm setup for them?

**Comment by le717** [comment]
There's only been a Mac in my house for a few months because dad bought one (and I've never used it), and Linux has only been used to recover from computer disasters. I'm sure it is possible, but I haven't the slightest clue. :P

**Comment by charlielee** [comment]
Closing this issue as I have recently began splitting it out into several others
