### ISSUE TITLE
Revised keyboard shortcuts

### ISSUE THREAD

**Issue by charlielee** [charlielee/boats-animator#91]
The repetitiveness of some aspects of stop motion animation make solid keyboard shortcuts a must for Boats Animator. A quirk of NW.js's menu API mean that with very little hassle the following shortcuts currently exist in BA:
- `Ctrl Z` = undo last frame
- `Ctrl C` = capture frame
- `Ctrl M` = return to launcher

These are not great for numerous reasons and need to revised to consider standard Mac and PC expectations amongst other things. Some suggestions I have for future and existing features are:

(note `NUM` refers to the keypad)
##### Projects
- [x] `Ctrl O` / `Cmd O` = open project
- [ ] `Ctrl S` / `Cmd S` = save project
- [ ] `Ctrl Shift S` / `Cmd Shift S` = save project as
- [x] `Ctrl N` / `Cmd N` = new scene
- [ ] `Ctrl Shift N` / `Cmd Shift N` = new take
- [x] `Ctrl W` / `Cmd W` = close window (and return to the launcher screen)
- [x] `Ctrl Q` / `Cmd Q` = quit program

_Project shortcuts will be added when #37 and #86 are implemented_
##### Controls
- [x] `Enter` / `NUM Enter` = Capture frame
- [x] `Ctrl Z` / `Cmd Z` / `Backspace` / `Delete` / `NUM *` = delete last frame captured
- [ ] `Ctrl Shift Z` / `Cmd Shift Z` / `Ctrl Delete` / `Cmd delete` = delete current selected frame in frame reel
- [x] `Ctrl M` / `Cmd M` / `M` = toggle audio
##### Playback
- [x] `Space` / `0` / `NUM 0` / `MediaPlayPause` = Play / pause
- [ ] `P` / `Num .` = Play from start
- [ ] `6` / `NUM 6` = Play last few captured frames
- [x] `8` / `NUM 8` = toggle looping
- [x] `Ctrl Right` / `MediaPrevTrack` = jump to the first frame on the framereel
- [x] `Ctrl Left` / `MediaNextTrack` = jump to the last frame on the framereel (ie stop)
  ##### Framereel
- [x] `left arrow` / `1` / `NUM 1` = back 1 frame on framereel
- [x] `right arrow` / `2` / `NUM 2` = forward 1 frame on framereel
- [x] `L` /  `3` / `NUM 3` = switch to live view
- [ ] `Ctrl +` / `Cmd +` = zoom into framereel
- [ ] `Ctrl -` / `Cmd -` = zoom out of framereel
- [ ] `Ctrl 0` / `Cmd 0` = return framereel to default zoom
- [ ] `Right click` (on an individual frame) = menu with option to delete frame or add keyframe.
##### Keyframes
- [ ] `i` = set currently selected frame as the start keyframe.
- [ ] `esc` = remove start keyframe

_Will be added when #122 is merged_
##### Onion skinning
- [ ] `+` / `NUM +` = move onion skinning slider to the right
- [ ] `-` / `NUM -` = move onion skinning slider to the left

_These will be added when #71 is implemented_
##### Confirm prompts
- [x] `Enter` = okay
- [x] `Esc` / `/` = cancel
##### Others
- [x] `F1` / `Cmd + Shift + ?` = load documentation
- [x] `F12` = load dev tools

I'm aware Mac and PC keypads have some minor differences and as a result have tried to avoid keys that do not appear on both. Here is a visual depiction of the shortcuts above:

<img width="400" alt="keypad1" src="https://cloud.githubusercontent.com/assets/8095888/11615685/873edfa4-9c5f-11e5-8f79-53b96adc91d9.png">
**_Note since creating the image above `/` has changed function to cancel confirm prompts rather than mute audio**_

In terms of implementing these [Mousetrap.js](https://craig.is/killing/mice) seems pretty neat.

**Comment by le717** [comment]
Drive-by comment: remove the milestone, make this more a progress/listing issue. We won't be getting all these in 0.7.x, but rather when features are added. ;)

**Comment by rioforce** [comment]
Looks fantastic.

**Comment by BoatsAreRockable** [comment]
I came across this yesterday:
https://github.com/nwjs/nw.js/wiki/Shortcut

Using a built in NW.js API seems preferable to something external like Mousetrap.

**Comment by BoatsAreRockable** [comment]
Actually mousetrap seems to allow a much greater range of keys than NW.js's API - better to stick to it.

**Comment by le717** [comment]
I noticed a number of boxes are checked. I assume you are implementing this on a local branch and will publish when done?

**Comment by le717** [comment]
Also, since we are going for mousetrap, install it using npm:

` npm install mousetrap --save`

I've been working on some build scripts for my new site. I'll try to pull them over here too to help us out. :)

**Comment by BoatsAreRockable** [comment]
> I assume you are implementing this on a local branch and will publish when done?

@le717 that is 100% correct ;)

**Comment by BoatsAreRockable** [comment]
Keyboard shortcuts to do:
* See if it is possible to create a system where the shortcut displayed next to a menubar item is taken from the first shortcut listed in `default-shortcuts.json`
* Custom keyboard shortcuts
