### ISSUE TITLE
Resolution changing

### ISSUE THREAD

**Issue by rioforce** [charlielee/boats-animator#92]
Didn't see an issue for this, so here it is.

I found this thing on the WebRTC site. It's a demo for webcam resolution changing. Looking through the code, it looks fairly simple to implement (though, I'm not a programmer, so, you know :P)

https://webrtc.github.io/samples/src/content/getusermedia/resolution/

I tested it on a Logitech c920 (which reaches 1080p, might even go higher, but the friend that tested it didn't have MonkeyJam installed, and that's what I use to find the highest resolution the camera supports). My QuickCamPro 9000 goes up to 720p (but actually goes a bit higher according to MonkeyJam, so we need to support that). All works well with this test, so I thought I'd send it over for someone to implement.

 IMO, (as you know) this would help to make the program more stable to use, because it takes frames and can kinda play them smoothly, so that'll help with testing while we implement other features like projects and such.

Tell me what you think! ;)

**Comment by le717** [comment]
Just wanted to say I have been working on drafting this up. It's been... rather interesting, to say the least. Hopefully I'll have some sort of code and build for you to test soon.

**Comment by rioforce** [comment]
How's it coming?

**Comment by charlielee** [comment]
Implemented in PR #211 🙂
